[build]
  functions = "functions"
  
 [[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "dist"
  
  
  
  [[redirects]]
  from = "/"
  to = "https://www.google.com"
  status = 200

